#http://github.com/nickvasilyev/Backgrounder
language: python
python:
  - "3.4"
before_script:
-  env
-  export PYTHONPATH=$PYTHONPATH:$(pwd)/Backgrounder
-  echo $PYTHONPATH 
script:
-  cd tests
-  python Backgrounder_unittests.py
